spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
#    data: classpath*:db/h2/data.sql
#    schema: classpath*:db/h2/schema.sql
  sql:
    init:
      schema-locations: classpath:*db/h2/schema.sql
      data-locations: classpath:*db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성은
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
#=======
#    show-sql: true      # (2) SQL ?? ??
#>>>>>>> 83a0c380e96c4c76a96b453a6bcb417bdc7fb8ff
